name: Protobuff-Compile-Test
on: [push]


jobs:
  build_and_test:
    name: go ${{ matrix.go_version }} pb-${{ matrix.protobuf_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: [1.13.x]
        protobuf_version: [3.9.1]
      fail-fast: false
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
        with:
          path: gopath/src/github.com/r3code/protobuf-multiple-packages-example
          fetch-depth: 5

      - name: Install go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go_version }}
          
      - name: Install protoc-go-gen
        run: go install github.com/golang/protobuf/protoc-gen-go

      - name: Install Protoc
        uses: Arduino/actions/setup-protoc@master
        with:
          version: ${{ matrix.protobuf_version }}

      - name: Protoc version
        run: PATH=$HOME/bin:$PATH protoc --version
        
      - name: Show ENV
        run: env && go env && pwd
        
      - name: Build example1
        run: cd example1 && bash ./proto-gen.sh

      - name: Build example2
        run: bash ./example2/proto-gen.sh


    
