name: Protobuff-Compile-Test
on: [push]


jobs:
  build_and_test:
    name: go ${{ matrix.go_version }} pb-${{ matrix.protobuf_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: [1.13.x]
        protobuf_version: [3.9.1]
      fail-fast: false
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
        with:
          path: gopath/src/github.com/r3code/protobuf-multiple-packages-example
          fetch-depth: 5

      - name: Install go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go_version }}
          
      - name: Install protoc-go-gen
        run: go get github.com/golang/protobuf/protoc-gen-go

      - name: Install Protoc
        uses: Arduino/actions/setup-protoc@master
        with:
          version: ${{ matrix.protobuf_version }}

      - name: Protoc version
        run: PATH=$HOME/bin:$PATH protoc --version
        
      - name: Show ENV
        run: env && go env && pwd
        
      - name: Compile Protobuf for example1
        working-directory: example1
        run: bash ./proto-gen.sh

      - name: Compile Protobuf for example2
        working-directory: example2
        run: bash ./proto-gen.sh
      
      - name: Show go files created 
        run: find . -name "*.go" 
      
      - name: Check go files created 
        run: bash count=`find . -name "*.go" | grep -c ".go"`; if [ $count -eq 0 ]; then echo "Fail. go files not found"; else echo "OK. Found $count go files";fi
      


    
